#https://github.com/elastic/elasticsearch/blob/main/distribution/docker/docker-compose.yml
version: '3.4'
services:
  elasticsearch-node:
    image: elasticsearch:8.5.3
    environment:
      - node.name=elasticsearch-node
      - discovery.type=single-node
      - cluster.name=elasticsearch-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - path.repo=/tmp/es-repo
      - cluster.routing.allocation.disk.watermark.low=1b
      - cluster.routing.allocation.disk.watermark.high=1b
      - cluster.routing.allocation.disk.watermark.flood_stage=1b
      - node.store.allow_mmap=false
      - ingest.geoip.downloader.enabled=false
      - xpack.security.enabled=false
      - xpack.security.transport.ssl.enabled=false
      - xpack.security.http.ssl.enabled=false
      - xpack.security.authc.token.enabled=false
      - xpack.security.audit.enabled=false
      - xpack.license.self_generated.type=trial
      - action.destructive_requires_name=false
      - cluster.deprecation_indexing.enabled=false
    ports:
      - "9200:9200"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    healthcheck:
      start_period: 15s
      test: ["CMD", "curl", "-f", "-u", "x_pack_rest_user:x-pack-test-password", "-k", "http://localhost:9200"]
      interval: 10s
      timeout: 2s
      retries: 5
  kafka:
    image: wurstmeister/kafka:2.12-2.5.0
    ports:
      - "9092:9092"
    environment:
      - KAFKA_ADVERTISED_HOST_NAME=localhost
      - KAFKA_ADVERTISED_PORT=9092
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
    depends_on:
      - zookeeper

  zookeeper:
    image: wurstmeister/zookeeper:3.4.6
    ports:
      - "2181:2181"